server:
  port: 8081

spring:
  profiles:
    active: local

  application:
    name: library-events-consumer

  kafka:
    topic: "library-events"
    listener:
      auto-startup: true
    consumer:
      bootstrap-servers:
        - localhost:9092
        - localhost:9094
        - localhost:9096
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: library-events-listener-group

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: postgres
    password: postgres
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
# http://localhost:8081/h2-console jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true